---
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0

workflows:
  btd_dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: argent-smith/opam
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
