---
description: |
  Executes a job in a given OPAM v2.* container

parameters:
  image:
    description: |
      Supposed to be OPAM v2.* official container name
    type: string
    default: "ocaml/opam2"

  tag:
    description: |
      Supposed to be OPAM v2.* docker image tag
    type: string
    default: "debian-stable"

  cache_depends:
    description: |
      Whether to cache dependencies
    type: boolean
    default: false

  depends_cache_reference_file:
    description: |
      File to use as a checksum reference for dependencies caching
    type: string
    default: ""

docker:
  - image: "<< parameters.image >>:<< parameters.tag >>"
